---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create Azure Deploy
      azure_rm_deployment:
        state: present
        resource_group_name: matiTest
        parameters:
          adminUsername:
            value: 'vmAdmin'
          adminPassword:
            value: '$4raZa093846' 
          dnsLabelPrefix:
            value: 'vm123943736'
        template_link: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vm-simple-linux/azuredeploy.json'
