---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Run Cli
      shell: >
           az login --service-principal
           -u " {{ AZURE_CLIENT_ID }}"
           -p "{{ AZURE_SECRET }}"
           --tenant "{{ AZURE_TENANT }}" && az group list -o table
      register: azlist

    - name: Debug
      debug:
        msg: "{{ azlist }}"
