---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Run Cli
      shell: az group list -o table
      register: azlist

    - name: Debug
      debug:
        msg: "{{ azlist }}"

      
